# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLypOrlZlOzCLS6bYhdWs9XGVTdYd9Cd
"""

import numpy as np
import pandas as pd

import tensorflow as tf
import tensorflow_hub as hub

import matplotlib.pyplot as plt

df_train = pd.read_csv('/tmp/train.csv')
df_test = pd.read_csv('/tmp/test.csv')
df_train.label = pd.factorize(df_train.label)[0]
df_test.label = pd.factorize(df_test.label)[0]

train_data = df_train.loc[:,'report'].values
train_label = df_train.loc[:,'label'].values
test_data = df_test.loc[:,'report'].values
test_label = df_test.loc[:,'label'].values

train_label = tf.keras.utils.to_categorical(train_label,5)
test_label = tf.keras.utils.to_categorical(test_label,5)

model = "https://tfhub.dev/google/nnlm-id-dim128/2"
hub_layer = hub.KerasLayer(model, input_shape=[], dtype=tf.string, trainable=True)

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(5, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy', metrics=['accuracy']
              )
model.summary()

num_epochs = 5
history = model.fit(train_data, train_label, epochs=num_epochs, validation_data=(test_data, test_label))

model.save('/tmp/classification_model')

!zip -r /tmp/classification.zip /tmp/classification_model